import type { AttendanceRecord } from './types';

export const MOCK_ATTENDANCE: AttendanceRecord[] = [
  {
    id: '1',
    timestamp: new Date('2024-07-10T10:00:00Z'),
    fullName: 'João da Silva',
    cpf: '11122233344',
    reclassification: 'Membro',
    pastorName: 'Pastor Antônio',
    region: 'Norte',
    churchPosition: 'Membro',
    city: 'São Paulo',
    shift: 'Manhã',
    status: 'Presente',
  },
  {
    id: '2',
    timestamp: new Date('2024-07-10T10:01:00Z'),
    fullName: 'Maria Oliveira',
    cpf: '22233344455',
    reclassification: 'Visitante',
    pastorName: 'Pastor Antônio',
    region: 'Sul',
    churchPosition: 'Outro',
    city: 'Rio de Janeiro',
    shift: 'Manhã',
    status: 'Presente',
  },
  {
    id: '3',
    timestamp: new Date('2024-07-10T19:00:00Z'),
    fullName: 'Pedro Souza',
    cpf: '33344455566',
    reclassification: 'Membro',
    pastorName: 'Pastor Carlos',
    region: 'Leste',
    churchPosition: 'Diácono',
    city: 'Belo Horizonte',
    shift: 'Noite',
    status: 'Presente',
  },
  {
    id: '4',
    timestamp: new Date('2024-07-09T19:05:00Z'),
    fullName: 'Ana Pereira',
    cpf: '44455566677',
    reclassification: 'Membro',
    pastorName: 'Pastor Carlos',
    region: 'Oeste',
    churchPosition: 'Membro',
    city: 'São Paulo',
    shift: 'Noite',
    status: 'Ausente',
  },
  {
    id: '5',
    timestamp: new Date('2024-07-08T14:00:00Z'),
    fullName: 'Lucas Ferreira',
    cpf: '55566677788',
    reclassification: 'Obreiro',
    pastorName: 'Pastor Marcos',
    region: 'Central',
    churchPosition: 'Presbítero',
    city: 'Salvador',
    shift: 'Tarde',
    status: 'Presente',
  },
  {
    id: '6',
    timestamp: new Date('2024-07-08T14:02:00Z'),
    fullName: 'Juliana Costa',
    cpf: '66677788899',
    reclassification: 'Membro',
    pastorName: 'Pastor Marcos',
    region: 'Norte',
    churchPosition: 'Membro',
    city: 'Curitiba',
    shift: 'Tarde',
    status: 'Justificado',
  },
   {
    id: '7',
    timestamp: new Date('2024-07-10T19:10:00Z'),
    fullName: 'Carlos Lima',
    cpf: '77788899900',
    reclassification: 'Membro',
    pastorName: 'Pastor Antônio',
    region: 'Sul',
    churchPosition: 'Membro',
    city: 'São Paulo',
    shift: 'Noite',
    status: 'Presente',
  },
  {
    id: '8',
    timestamp: new Date('2024-07-10T10:15:00Z'),
    fullName: 'Fernanda Almeida',
    cpf: '88899900011',
    reclassification: 'Visitante',
    pastorName: 'Pastor Antônio',
    region: 'Leste',
    churchPosition: 'Outro',
    city: 'Brasília',
    shift: 'Manhã',
    status: 'Presente',
  },
  {
    id: '9',
    timestamp: new Date('2024-07-07T10:00:00Z'),
    fullName: 'Ricardo Martins',
    cpf: '99900011122',
    reclassification: 'Membro',
    pastorName: 'Pastor Carlos',
    region: 'Oeste',
    churchPosition: 'Diácono',
    city: 'Porto Alegre',
    shift: 'Manhã',
    status: 'Presente',
  },
   {
    id: '10',
    timestamp: new Date('2024-07-06T19:00:00Z'),
    fullName: 'Beatriz Santos',
    cpf: '12312312312',
    reclassification: 'Membro',
    pastorName: 'Pastor Carlos',
    region: 'Central',
    churchPosition: 'Membro',
    city: 'São Paulo',
    shift: 'Noite',
    status: 'Ausente',
  },
];
